image:
  tag: 1.0.2
config:
  sonarr:
    - name: tv
      url: https://sonarr.tld:8989
      api_key: not-a-real-api-key
      renamarr:
        enabled: true
        hourly_job: true
        analyze_files: true
      series_scanner:
        enabled: false
        hourly_job: false
    - name: anime
      url: https://sonarr-anime.tld:8989
      api_key: not-a-real-api-key
      renamarr:
        enabled: false
        hourly_job: false
        analyze_files: false
      series_scanner:
        enabled: true
        hourly_job: true
        hours_before_air: 1
  radarr:
    - name: radarr
      url: https://radarr.tld:7878
      api_key: not-a-real-api-key
      renamarr:
        enabled: true
        hourly_job: true
        analyze_files: false
    - name: radarr-4k
      url: https://radarr-4k.tld:7878
      api_key: not-a-real-api-key
      renamarr:
        enabled: true
        hourly_job: true
        analyze_files: true